---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/capegardenscom/public_html
    - /usr/bin/rsync -av --exclude='.git' --exclude='.gitignore' --exclude='.gitattributes' --exclude='vendor' ./ $DEPLOY_PATH
