---
deployment:
  tasks:
    - export DEPLOYPATH=/home/capegardenscom/public-html/
    - /usr/bin/rsync -av --exclude='.git' --exclude='.gitignore' --exclude='.gitattributes' --exclude='vendor' --exclude='node_modules' ./ $DEPLOYPATH
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - chown -R capegardenscom:capegardenscom $DEPLOYPATH